/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grupo4.proyectoaccesodatos.vista.InterfazesProfesor.InterfazesEliminar;

import grupo4.proyectoaccesodatos.modelo.ConsultasProfesor.ConsultasEliminar.ConsultaEliminarNota;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diurno
 */
public class InterfazEliminarNota extends javax.swing.JFrame {

    private final String usuario;
    private final ConsultaEliminarNota consultaNotas;

    /**
     * Creates new form InterfazEliminarNota
     */
    public InterfazEliminarNota(String usuario) {
        initComponents();
        this.usuario = usuario;
        tablaNotas.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String[]{
                    "Nombre", "Apellido", "Asignatura", "Nota"
                }
        ));
        consultaNotas = new ConsultaEliminarNota();

        // Cargar las notas del usuario (profesor)
        cargarNotas();
    }

    private void cargarNotas() {
        int usuarioId = consultaNotas.obtenerIdUsuarioPorEmail(usuario);

        if (usuarioId != -1) {
            // Obtener las notas para el profesor usando el id del usuario
            Object[][] notas = consultaNotas.obtenerNotasPorProfesor(usuarioId);

            // Obtener el modelo de la tabla para insertar las filas
            DefaultTableModel model = (DefaultTableModel) tablaNotas.getModel();

            // Limpiar la tabla antes de agregar nuevas filas
            model.setRowCount(0);

            // Si encontramos notas, agregarlas a la tabla
            if (notas != null && notas.length > 0) {
                for (Object[] fila : notas) {
                    model.addRow(fila);
                }
            } else {
                JOptionPane.showMessageDialog(this, "No se encontraron notas para este profesor.", "Información", JOptionPane.INFORMATION_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró el usuario con ese email.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaNotas = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SELECCIONA LA NOTA QUE QUIERES ELIMINAR");

        tablaNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaNotas);

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(btnEliminar)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int filaSeleccionada = tablaNotas.getSelectedRow();

        if (filaSeleccionada != -1) { // Verificar que se haya seleccionado una fila
            // Obtener los valores de la fila seleccionada
            int notaId = (int) tablaNotas.getValueAt(filaSeleccionada, 0); // Asumiendo que la primera columna es el ID de la nota
            String alumnoNombre = (String) tablaNotas.getValueAt(filaSeleccionada, 1); // Nombre del alumno
            String alumnoApellido = (String) tablaNotas.getValueAt(filaSeleccionada, 2); // Apellido del alumno
            String asignatura = (String) tablaNotas.getValueAt(filaSeleccionada, 3); // Asignatura

            // Mostrar estos valores por consola (esto es solo para fines de depuración)
            System.out.println("Nota ID: " + notaId);
            System.out.println("Alumno: " + alumnoNombre + " " + alumnoApellido);
            System.out.println("Asignatura: " + asignatura);

            // Eliminar la fila de la base de datos
            boolean eliminado = consultaNotas.eliminarNota(notaId);

            if (eliminado) {
                // Si la eliminación fue exitosa, eliminar la fila de la tabla también
                DefaultTableModel model = (DefaultTableModel) tablaNotas.getModel();
                model.removeRow(filaSeleccionada); // Eliminar la fila de la tabla
                JOptionPane.showMessageDialog(this, "Nota eliminada con éxito.", "Información", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Hubo un problema al eliminar la nota.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona una fila para eliminar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazEliminarNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazEliminarNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazEliminarNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazEliminarNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                String usuario = null;
                new InterfazEliminarNota(usuario).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaNotas;
    // End of variables declaration//GEN-END:variables
}
